### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Mobile App Landing Page Template
email: username@email.com
description: Free to use static landing page template to showcase your mobile app
baseurl: "/application-landingpage" # the subpath of your site, e.g. /blog
url: "https://jame-louis.github.io" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
github_username:  jame-louis
author: Jame Louis
logo: assets/images/large-logo.png
social:
  name: Jame Louis
  links:
    - https://github.com/jame-louis

languages: ["en"]
ampdir: amp

github: https://github.com/jame-louis/application-landingpage

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
